src/Entity/Link.php
<?php

namespace App\Entity;

use App\Repository\LinkRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LinkRepository::class)]
class Link
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Url = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?LinkType $Type = null;

    #[ORM\ManyToOne(inversedBy: 'Links')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Artist $Artist = null;

    #[ORM\ManyToOne(inversedBy: 'Links')]
    private ?Crew $Crew = null;

    #[ORM\ManyToOne(inversedBy: 'Links')]
    private ?Post $Post = null;

    #[ORM\ManyToOne(inversedBy: 'Links')]
    private ?Club $Club = null;

    public function __toString(): string
    {
        return $this->Type->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->Url;
    }

    public function setUrl(string $Url): static
    {
        $this->Url = $Url;

        return $this;
    }

    public function getType(): ?LinkType
    {
        return $this->Type;
    }

    public function setType(?LinkType $Type): static
    {
        $this->Type = $Type;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->Artist;
    }

    public function setArtist(?Artist $Artist): static
    {
        $this->Artist = $Artist;

        return $this;
    }

    public function getCrew(): ?Crew
    {
        return $this->Crew;
    }

    public function setCrew(?Crew $Crew): static
    {
        $this->Crew = $Crew;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->Post;
    }

    public function setPost(?Post $Post): static
    {
        $this->Post = $Post;

        return $this;
    }

    public function getClub(): ?Club
    {
        return $this->Club;
    }

    public function setClub(?Club $Club): static
    {
        $this->Club = $Club;

        return $this;
    }
}

src/Entity/Post.php
<?php //src/Entity/Post.php

namespace App\Entity;

use App\Entity\Tag;
use App\Entity\Artist;
use DateTimeImmutable;
use App\Entity\Podcast;
use App\Entity\Interview;
use App\Config\PostStatus;
use App\Entity\RecSession;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PostRepository;
use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\MappedSuperclass;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[MappedSuperclass]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity('Slug')]
#[ORM\Table(name: 'post')]
#[InheritanceType('SINGLE_TABLE')]
#[DiscriminatorColumn(name: 'post_type', type: 'string')]
#[DiscriminatorMap([
    'post' => Post::class, 
    'orbiter_session' => OrbiterSession::class,
    'radio' => Radio::class,
    'teletime' => Teletime::class,
    'windowlicker' => Windowlicker::class,
    'podcast'=> Podcast::class,
    'neben_der_spur'=> NebenDerSpur::class,
    'rec_session'=> RecSession::class,
    'interview'=> Interview::class,    
])]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    protected ?int $id = null;

    #[ORM\Column(nullable: true, enumType: PostStatus::class)]
    protected ?PostStatus $Status = PostStatus::Draft;

    #[ORM\Column(length: 255)]
    protected ?string $Title = null;

    #[ORM\Column(length: 255)]
    protected ?string $Slug = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    protected ?string $Description = null;

    #[ORM\Column(type: 'easy_media_type', nullable: true)]
    protected ?string $Image = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    protected ?\DateTimeInterface $Date = null;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'Posts')]
    protected Collection $Tags;

    #[ORM\ManyToMany(targetEntity: Artist::class, inversedBy: 'Posts')]
    private Collection $Artists;

    #[ORM\ManyToMany(targetEntity: Crew::class, inversedBy: 'Posts')]
    private Collection $Crews;

    #[ORM\ManyToOne(inversedBy: 'Posts')]
    private ?User $User = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $editedAt = null;

    #[ORM\OneToMany(mappedBy: 'Post', targetEntity: Link::class, cascade: ['persist'])]
    private Collection $Links;

    #[ORM\Column(type: 'easy_media_type', nullable: true)]
    private $AudioFile = null;

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function updatedTimestamps(): void
    {
        $dateTimeNow = new DateTimeImmutable('now');

        $this->setEditedAt($dateTimeNow);

        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }

    public function __construct()
    {
        $this->Tags = new ArrayCollection();
        $this->Artists = new ArrayCollection();
        $this->Crews = new ArrayCollection();
        $this->Links = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->Title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): static
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): static
    {
        $this->Date = $Date;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->Tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->Tags->contains($tag)) {
            $this->Tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        $this->Tags->removeElement($tag);

        return $this;
    }

    /**
     * @return Collection<int, Artist>
     */
    public function getArtists(): Collection
    {
        return $this->Artists;
    }

    public function addArtist(Artist $artist): static
    {
        if (!$this->Artists->contains($artist)) {
            $this->Artists->add($artist);
        }

        return $this;
    }

    public function removeArtist(Artist $artist): static
    {
        $this->Artists->removeElement($artist);

        return $this;
    }

    /**
     * @return Collection<int, Crew>
     */
    public function getCrews(): Collection
    {
        return $this->Crews;
    }

    public function addCrew(Crew $crew): static
    {
        if (!$this->Crews->contains($crew)) {
            $this->Crews->add($crew);
        }

        return $this;
    }

    public function removeCrew(Crew $crew): static
    {
        $this->Crews->removeElement($crew);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getEditedAt(): ?\DateTimeImmutable
    {
        return $this->editedAt;
    }

    public function setEditedAt(?\DateTimeImmutable $editedAt): static
    {
        $this->editedAt = $editedAt;

        return $this;
    }

    /**
     * @return Collection<int, Link>
     */
    public function getLinks(): Collection
    {
        return $this->Links;
    }

    public function addLink(Link $link): static
    {
        if (!$this->Links->contains($link)) {
            $this->Links->add($link);
            $link->setPost($this);
        }

        return $this;
    }

    public function removeLink(Link $link): static
    {
        if ($this->Links->removeElement($link)) {
            // set the owning side to null (unless already changed)
            if ($link->getPost() === $this) {
                $link->setPost(null);
            }
        }

        return $this;
    }

    public function getAudioFile()
    {
        return $this->AudioFile;
    }

    public function setAudioFile($AudioFile): static
    {
        $this->AudioFile = $AudioFile;

        return $this;
    }

    public function getStatus(): ?PostStatus
    {
        return $this->Status;
    }

    public function setStatus(?PostStatus $Status): static
    {
        $this->Status = $Status;

        return $this;
    }
}

templates/components/Crud/Actions.html.twig
<div class="global-actions">
    {% for action in this.actions %}
        <a 
            class="action-{{ action.title|lower }} btn btn-secondary btn-sm"

            {{ stimulus_controller('modal', {
                'url': path(action.path),
                'resolve': action.name
            })}}

            data-action="modal#openModal"
            data-bs-target="modal">
            <span class="action-label text-white">{{ action.title|capitalize }} {{ this.title }}</span></a>
    {% endfor %}
</div>

templates/components/Crud/Crud.html.twig
<article class="w-100">
    <section class="content-header d-flex justify-content-between mb-3">
        {% block content_title %}
            <div class="content-header-title">
                {{ component('Crud:Title', {
                    title: this.title,
                }) }}
            </div>
        {% endblock %}
        {% block content_actions %}
            <div class="page-actions mb-3">
                {{ component('Crud:Actions', {
                    actions: this.actions,
                    title: this.title,
                    path_url: this.path_url,
                }) }}
            </div>
        {% endblock %}
    </section>
    <section id="main" class="content-body">
        {% block content_table %}
            {{ component('Crud:Table', {
                posts: this.posts,
                table: this.table,
                path_url: this.path_url,
                title: this.title,
                noItemsText: this.noItemsText,
            }) }}
        {% endblock %}
    </section>
</article>

templates/components/Crud/Icon.html.twig
{% if this.level.value == 'error' %}
    {% set level = 'danger' %}
{% else %}
    {% set level = this.level.value %}
{% endif %}

{% if this.level.value == 'info' or this.level.value == 'success' %}
    {% set icon = 'info' %}
{% elseif this.level.value == 'warning' %}
    {% set icon = 'question' %}
{% else %}
    {% set icon = 'exclamation' %}
{% endif %}

<span class="d-flex align-items-center justify-content-center badge rounded rounded-circle bg-{{ level }}{% if this.subtle %}-subtle{% endif %}" style="width:24px; height:24px;">
    <i class="fa-solid fa-{{ icon }}"></i>
</span>

templates/components/Crud/Notification.html.twig
<li class="list-group-item list-group-item-action {% if this.post.Status.value == 'read' %}disabled pe-none opacity-50{% endif %} mb-2">
    <div class="d-flex align-items-center justify-content-between gap-3">
        <div class="">
            {{ component('Crud:Icon', { 
                level: this.post.Level,
                subtle: false,
            }) }}
        </div>
        <div class="text-wrap small flex-grow-1">{{ this.post.Text|raw }}</div>
        <div class="small fw-light">{{ this.post.createdAt|time_diff }}</div>
        <div class="">
            <a 
                href="#" 
                {{ stimulus_controller('notification', {
                    'url': path('app_user_notification_mark', { 'id':this.post.id }),
                    'token': csrf_token('mark-as-read')
                }) }}
                data-action="notification#markAsRead" 
                class="{% if this.post.Status.value == 'read' %}pe-none{% endif %}">
                    <i class="fa-solid fa-bell {% if this.post.Status.value == 'read' %}text-secondary{% endif %}"></i>
            </a>
        </div>
    </div>
</li>

templates/components/Crud/SinglePost.html.twig
<li class="d-flex p-2 list-group-item list-group-item-action animate__animated animate__fadeIn">
    <div class="w-100 d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center gap-3">
            {{ component('Card:Image', { 
                image: post.Image|default(''),
                corner_style: 'rounded border',
                style: 'thumbnail',
                width: 48,
                load: ''
            }) }}
            <h5 class="p-0 m-0">{{ post.Name }}
                {% if post.isVerified %}
                    <span 
                        data-filter-verified="true"
                        data-bs-toggle="tooltip" 
                        data-bs-title="Verified"
                    >
                        <i class="fa-solid fa-circle-check text-info me-2"></i>
                    </span>
                {% endif %}
            </h5>
        </div>
        <div class="dropdown">
            <a class="btn btn-outline-secondary btn-sm py-1 px-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-ellipsis"></i>
            </a>

            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="">View</a></li>
                <li><a class="dropdown-item" href="">Edit</a></li>
            </ul>
        </div> 
    </div>
</li>

templates/components/Crud/Table.html.twig
<ul id="list" class="list-group" {{ stimulus_controller('tooltip') }}>
    {% for post in posts %}
        {% if constant('class', post) == 'App\\Entity\\Artist' %}
            <ul id="list" class="list-group" data-controller="tooltip">
                {{ component('Crud:SinglePost', {
                    post:post,
                    path_url: this.path_url,
                }) }}
            </ul>
        {% endif %}

        {% if constant('class', post) == 'App\\Entity\\Crew' %}
            <ul id="list" class="list-group" data-controller="tooltip">
                {{ component('Crud:SinglePost', {
                    post:post,
                    path_url: this.path_url,
                }) }}
            </ul>
        {% endif %}

        {% if constant('class', post) == 'App\\Entity\\Notification' %}
            <div class="list-group">
                {{ component('Crud:Notification', {
                    post:post,                  
                }) }}
            </div>
        {% endif %}
    {% else %}
        <a  class="d-flex p-3 list-group-item list-group-item-action animate__animated animate__fadeIn pe-none"
            href="#">
            <div class="w-100 d-flex gap-3">
                <div class="">{{ this.noItemsText }}</div>
            </div>
        </a>
    {% endfor %}
</ul>

templates/components/Crud/Title.html.twig
<h3 class="title">My {{ this.title }}s</h3>